# config/packages/knp_paginator.yaml

knp_paginator:
  page_range: 5                      # Number of pages displayed in the pagination bar
  default_options:
    page_name: page                # Page query parameter name
    sort_field_name: sort          # Sort query parameter name
    sort_direction_name: direction # Sort direction query parameter name
    distinct: true                 # Ensure distinct results
  template:
    pagination: 'shared/_paginator.html.twig'
